### ISSUE TITLE
TODO: 

### ISSUE THREAD

**Issue by TMichaelan** [TMichaelan/workout-application-put#2]
- [x] Спроектировать базу данных
- [x] Найти API для заполнения базы данных
- [x] Выкачать данные из API в локальную базу данных
- [x] Расширить search bar , чтобы можно было кликать на всю область поиска
- [x] Убрать отображение списка, если нет совпадений 
- [x] Перенести иконку поиска вправо
- [x] Добавить фунцию удаления тренировки
- [x] Поправить ошибки с картой
- [x] Скрол карты по оси Х и добавить падинги( сделать специальный блок для карты)
- [x] Добавить отступы (сделать как карточки) кнопки в recycler view
- [x] Добавить регистрацию пользователей 
- [x] Добавить активити регистрации с возможностью не регистрироваться.
- [x] Добавить анимацию при запуске приложения
- [x] Добавить на третьем табе проверку на регистрацию пользователя
- [x] Добавить не локальную базу данных для сохранения пользователя и его тренировок
- [x] В локальной базе данных по итогу должны быть по 20 упражнений каждой части тела, остальные подгружать с API
- [x] После добавления упражнений в локальную БД, сделать проверку на дубликаты(чтобы с API и локальной) не пересекались (либо если есть интернет все с API, нет инета все с локальной БД) 
- [x] Переделать дизайн
- [x] Добавить валидацию на username, email
- [x] Добавить хэширование пароля
- [x] Добавить активити с деталями упражнения
- [x] Добавить фрамент с тренировками 
- [x] Изменить home фрагмент на упражнения из локальной базы данных
- [x] придумать что делать с динамическими ссылками на гифки из API
- [x] подключить новый API ключ
- [x] !!!!!!придумать что хранить на локальной базе данных (BMI?)
- [x] Добавить функцию добавления упражнения в определённую тренировку UPD. Правильно инкрементить упражнения(требует много операций) / уникальный ID для каждого упражнения (непонятно выглядит)
- [x] Добавить функцию удаления упражнения из определённой тренировки
- [x] Добавить функцию изменения названия тренировки
- [x] Добавить загрузку пока загружается карта (карта + локация пользователя + маркеры)
- [x] Добавить загрузку в splashActivity пока берутся данные для рандомных упражнений из Firebase + Workouts пользователя
- [x] Придумать что-то в HomeActivity для локальной базы данных, чтобы работало без интернета.
- [x] Добавить валидацию при регистрации пользователя на длину username, нельзя больше 15-20 символов
- [x] SplashActivity fix - когда нажимаешь кнопку назад, она появляется
- [x] Добавить везде "No internet коннекшн" если не выключен интернет и программа не может получить данные о тренировках и тд (ошибка по типу Log In to use this functionality)
- [x] Фикс краша, когда нет интернета и пользователь пытается получить упражнения из API
- [x] Добавить кнопку в тулбаре с предложенными (встроенными в локальную дб) тренировками
- [x] Фикс, что после добавления упражнений в тренировку, пользователя перекидывает в MainActivity
- [x] Добавить возможность с помощью кнопки + в Details к упражнению добавить упражнение в локальную базу данных для отображения в our exersises
- [x] Переделать layout в our exersises
- [x] Добавить Details exersises в our exersises
- [x] GIF должна скачиваться и добавлять в DB для our exersises
- [x] Заменить кнопку + в details на сердечко, если упражнение уже есть в локальной DB то сердечко выделено, убрав выделение ты удаляешь упражнение из DB. (как лайк и добавление в локалку в приложении с рецептами)
- [x] fix переименовывания тренировки
- [x] fix сердечка (оно уродское)
- [x] Когда нет интернета гифки в хоум фрагменте рандомные, поменять на стандартную картинку
- [x] fix тыканья на сердечко по КД вызывает краш (проблема из-за скачивания и удаления гифок скорее всего)
- [x] Добавить загрузку во время перехода по частям тела, в ожидание на получение данных из API / либо заменить обращение к API на поиск из JSON
- [x] Добавить иконку приложения
- [x] Закоментить Log.d выводы
- [x] Добавить спинер во время авторизации и регистрации в Log In
- [x] Добавить спинер во время загрузки упражнений в workout
- [ ] Когда добавляешь в упражнение в workout, объект берется с API в котором динамическая ссылка на гифку, т.е. через какое-то время гифка пропадает.
